name:                python-parser
version:             0.1.0.0
github:              "moses-alexander/python-parser"
license:             BSD3
author:              "moses alexander"
maintainer:          "esotericgravity@gmail.com"
copyright:           "2019 moses alexander"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/moses-alexander/python-parser#readme>

dependencies:
- base >= 4.7 && < 5
- parsec

library:
  source-dirs: src
  exposed-modules:
  - Features
  - Test

executables:
  python-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    dependencies:
    - python-parser
    - parsec
    - hlint
    extensions:
    - FlexibleContexts

tests:
  python-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - python-parser
